### PR TITLE
Remove CVec

### PR DESCRIPTION
**Pull request by daym**
CVec dev-depends on libc 0.1 which I can't compile using rustc 1.14.0 because of

```
   Compiling libc v0.1.12 (file:///tmp/guix-build-rust-libc-0.1.12.drv-0/libc-0.1.12)
error[E0554]: #[feature] may not be used on the stable release channel
  --> rust/src/liblibc/lib.rs:26:19
   |
26 | #![cfg_attr(test, feature(test))]
   |                   ^^^^^^^^^^^^^

error: aborting due to previous error
```

The current libc is 0.2 which is incompatible with 0.1.

Only 8 Rust crates in total seem to still use c_vec - and many moved away.

Therefore, I removed c_vec from cairo-rs.

Note that I'm a beginner to Rust. However, the compilation worked and all the tests run by `cairo test` still pass.

The parts that still used CVec were:

- src/context.rs: `copy_clip_rectangle_list` which calls an FFI function which returns newly allocated memory, eventually freed via impl Drop (by us). Therefore, the lifetime of the newly allocated memory is the same as ours.
- src/paths.rs: `iter`: the PathSegments are part of the Path and therefore live as long as the Path does.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Such a change is quite problematic due to the high unsafety of the from_raw_parts method. Personnally, I'm against this change. What do you think about it @EPashkin?

**Comment by EPashkin** [comment]
@GuillaumeGomez, currently I also against merging this PR.
IMHO Better solution will be publishing `c_vec 1.0.13` which already updated libc dependence in code but just not published.

File: src/context.rs [hunk 1]
```diff
@@ -26,12 +26,12 @@ use ffi::enums::{Status, Antialias, LineCap, LineJoin, FillRule};
 use ::patterns::{wrap_pattern, Pattern};
 use surface::Surface;
 
-pub struct RectangleVec {
+pub struct RectangleVec<'a> {
     ptr: *mut cairo_rectangle_list_t,
-    pub rectangles: CVec<Rectangle>,
+    pub rectangles: &'a[Rectangle], // Vec<Rectangle>,
 }
```
Comment (EPashkin) [inline src/context.rs]: `RectangleVec` filled from `Context::copy_clip_rectangle_list` may outlive source, so use lifetime may cause problems.

Comment (daym) [inline src/context.rs]: What do you mean? I thought that we freed RectangleVec ourselves.

Also, RectangleVec.rectangles is created at the same time as the RectangleVec instance and also freed at the same time as the RectangleVec instance. In short, RectangleVec and RectangleVec.rectangles have the same lifetime.

Am I wrong in this? Or do you mean that the RectangleVec instance can be copied? If so, that's bad...

Comment (EPashkin) [inline src/context.rs]: Line `pub fn copy_clip_rectangle_list(&self) -> RectangleVec {` with your version of `RectangleVec` actually mean `pub fn copy_clip_rectangle_list<'a>(&'a self) -> RectangleVec<'a> {`
So borrow checker think that `RectangleVec` can't outlive `Context` object for that function was called.
In most cases is not problem, but if you need store this vector for long time borrow checker nags about lifetimes.
PS. No, `RectangleVec` instance can't be copied, as it don't realize `Clone, Copy` in cairo crate, and has private member, that disallow create objects of this type outside

Comment (daym) [inline src/context.rs]: >So borrow checker think that RectangleVec can't outlive Context object for that function was called.

... what magic is this? But good to know. Yeah, my intent was to have it be a refcounted object independent of Context (I checked cairo's copy_clip_rectangle_list - it just mallocs a list). But apparently that works in a different way. Sorry.

Comment (EPashkin) [inline src/context.rs]: https://doc.rust-lang.org/book/lifetimes.html#lifetime-elision
By way, @daym, it solves your problem if @GuillaumeGomez publish `c_vec` with upgraded `lib_c` dependence?

Comment (daym) [inline src/context.rs]: It should. I'll test it.

**Comment by GuillaumeGomez** [comment]
I'll try to do the update in the next hours.

**Comment by GuillaumeGomez** [comment]
I merged the [PR](https://github.com/GuillaumeGomez/c_vec-rs/pull/16). Updating cairo dependency.

**Comment by GuillaumeGomez** [comment]
@daym: Maybe you could try https://github.com/gtk-rs/cairo/pull/98 ?
